### ISSUE TITLE
error FS0039: The value or constructor 'TestFile' is not defined

### ISSUE THREAD

**Issue by ruslander** [Elders/Pandora#3]
Hey,

I cloned the project and ran the build.bat. Getting an error, maybe is something obvious but could not figure out why. What are the prerequisites ?

Here is the output

`C:\Users\Ruslan\Documents\Pandora>build.cmd
Downloading latest version of NuGet.exe...
Downloading latest version of FAKE...
Downloading latest version of NuGet.Core...
Downloading latest version of GitVersion.CommandLine...
Downloading latest version of Nyx...
Package "Nyx" is already installed.

F# Interactive for F# 4.0 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx]

C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx(224,48): error FS0039: The value or constructor 'TestFile' is not defined

F# Interactive for F# 4.0 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx]

C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx(224,48): error FS0039: The value or constructor 'TestFile' is not defined

F# Interactive for F# 4.0 (private)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> [Loading C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx]

C:\Users\Ruslan\AppData\Local\Nyx\tools\build.fsx(224,48): error FS0039: The value or constructor 'TestFile' is not defined`

**Comment by mynkow** [comment]
Yes, we did some breaking changes to our build script. I also added some docs for Pandora and its purpose.

- update the master branch
- delete `C:\Users\user\AppData\Local\Nyx`
- should work

PS: probably you want to see this code: https://github.com/Elders/Cronus.Persistence.Cassandra/tree/master/playground

**Comment by ruslander** [comment]
thank you!
